-- require('plugin_config/treesitter')
-- 
-- require('plugin_config/nvimTree')
-- require('plugin_config/aerial')
-- -- require('plugin_config/symbols-outline')
-- 
-- require('plugin_config/telescope')
-- 
-- require('plugin_config/lua-line')
-- require('plugin_config/bufferline')
-- 
-- require('plugin_config/comment')
-- 
-- require('plugin_config/nvim-ufo')
-- 
-- require('plugin_config/prettier')
-- --require('plugin_config/null-ls')
-- --require('tab-line')
-- --require('vim-airline')
-- --require('vim-airline-themes')
-- require('plugin_config/gitsigns')
-- 
-- require('plugin_config/nvim-autopairs-settings')
-- require('plugin_config/nvim-ts-autotag')
-- 
-- -- color scheme
-- -- require('gruvbox')
-- -- require('plugin_config/onedark')
-- -- require('plugin_config/onedarkpro')
-- require('plugin_config/catppuccin')
-- require('plugin_config/transparent')
-- 
-- --require('coc')
-- -- require('tabnine')
-- -- require('plugin_config/cmp-tabnine')
-- require('plugin_config/nvim-copilot')
-- require('plugin_config/copilot-chat')
-- require('plugin_config/nvim-lspconfig')
-- require('plugin_config/nvim-cmp')
-- require('plugin_config/highlight-colors')
-- require('plugin_config/debugging')
-- require('plugin_config/indent-blankline')
-- require('plugin_config/markdown-preview')
